# Generated by Django 4.1.4 on 2023-07-08 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='captures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courrier_Univ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmetteur', models.CharField(choices=[('Sercice du doyen', 'Sercice du doyen'), ('Sercice de la scolarité', 'Sercice de la scolarité'), ('Chef de département', 'Chef de département'), ('Sercice des questeurs', 'Sercice des questeurs'), ('AUTRES...', 'AUTRES...')], max_length=150)),
                ('recepteur', models.CharField(choices=[('DECANAT', 'DECANAT'), ('Sercice des questeurs', 'Sercice des questeurs')], max_length=100)),
                ('types', models.CharField(choices=[('LETTRE(L)', 'LETTRE(L)'), ('REQUETE(R)', 'REQUETE(R)'), ('NOTE(N)', 'NOTE(N)')], max_length=100)),
                ('structure', models.CharField(blank=True, choices=[('UNIVERSITE DE YAOUNDE 1', 'UNIVERSITE DE YAOUNDE 1')], max_length=100, null=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('annee', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('objet', models.CharField(max_length=10000)),
                ('service_traitement', models.CharField(choices=[('Sercice du doyen', 'Sercice du doyen'), ('Sercice de la scolarité', 'Sercice de la scolarité'), ('Chef de département', 'Chef de département'), ('Sercice des questeurs', 'Sercice des questeurs')], max_length=150)),
                ('mention', models.CharField(blank=True, choices=[('ACCORD', 'ACCORD'), ('ETUDE ET COMPTE RENDU', 'ETUDE ET COMPTE RENDU'), ('ME VOIR', 'ME VOIR'), ('M EN PARLER', 'M EN PARLER'), ('REJET', 'REJET'), ('AUTRES', 'AUTRES')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courrier_univ',
            },
        ),
        migrations.CreateModel(
            name='Scan_Univ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
