# Generated by Django 4.1.3 on 2022-11-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitter', models.CharField(max_length=100)),
                ('reciever', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('objet', models.CharField(max_length=10000)),
            ],
        ),
    ]
