# Generated by Django 4.1.4 on 2023-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmetteur', models.CharField(choices=[('Cabinet du président su Sénat(CABPSEN)', 'Cabinet du président su Sénat(CABPSEN)'), ('Sécrétaire Général(SG)', 'Sécrétaire Général(SG)'), ('Sécrétaire Général Adjoint 1(SGA1)', 'Sécrétaire Général Adjoint 1(SGA1)'), ('Sécrétaire Général Adjoint 2(SGA2)', 'Sécrétaire Général Adjoint 2(SGA2)'), ('Conseillé technique(CT)', 'Conseillé technique(CT)'), ('Chargé de mission(CM)', 'Chargé de mission(CM)'), ('Direction des missions internationales(DMI)', 'Direction des missions internationales(DMI)'), ('Direction des servides techniques commun(DSTC)', 'Direction des servides techniques commun(DSTC)'), ('Direction du budget de la solde(DBS)', 'Direction du budget de la solde(DBS)'), ('Direction agence comptable(AC)', 'Direction agence comptable(AC)'), ('Direction des actions sociales et médicales(DASM)', 'Direction des actions sociales et médicales(DASM)'), ("Direction de la traduction de l'interpretation(DTI)", "Direction de la traduction de l'interpretation(DTI)"), ('Direction de la coordination des services ratachés et des relations internationales', 'Direction de la coordination des services ratachés et des relations internationales'), ('Direction de la collectivité territorial décentralisées(DCTD)', 'Direction de la collectivité territorial décentralisées(DCTD)'), ('Direction des ressources humaines(DRH)', 'Direction des ressources humaines(DRH)'), ('Sercice du doyen', 'Sercice du doyen'), ('Sercice de la scolarité', 'Sercice de la scolarité'), ('Chef de département', 'Chef de département'), ('Sercice des questeurs', 'Sercice des questeurs'), ('AUTRES...', 'AUTRES...')], max_length=150)),
                ('recepteur', models.CharField(choices=[('CABINET DU PRESIDENT DU SENAT', 'CABINET DU PRESIDENT DU SENAT'), ('SECRETARIAT GENERAL', 'SECRETARIAT GENERAL'), ('DECANAT', 'DECANAT'), ('Sercice des questeurs', 'Sercice des questeurs')], max_length=100)),
                ('types', models.CharField(choices=[('LETTRE(L)', 'LETTRE(L)'), ('REQUETE(R)', 'REQUETE(R)'), ('LOI(LN)', 'LOI(LN)'), ('DECISION(D)', 'DECISION(D)'), ('NOTE(N)', 'NOTE(N)'), ('PROJET DE LOI(PJL)', 'PROJET DE LOI(PJL)'), ('PROPOSITION DE LOI(PL)', 'PROPOSITION DE LOI(PL)'), ('ARRETE DE BUREAU(AB)', 'ARRETE DE BUREAU(AB)')], max_length=100)),
                ('structure', models.CharField(blank=True, choices=[('SENAT', 'SENAT'), ('UNIVERSITE DE YAOUNDE 1', 'UNIVERSITE DE YAOUNDE 1')], max_length=100, null=True)),
                ('code', models.CharField(max_length=100)),
                ('annee', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('objet', models.CharField(max_length=10000)),
                ('service_traitement', models.CharField(choices=[('Cabinet du président su Sénat(CABPSEN)', 'Cabinet du président su Sénat(CABPSEN)'), ('Sécrétaire Général(SG)', 'Sécrétaire Général(SG)'), ('Sécrétaire Général Adjoint 1(SGA1)', 'Sécrétaire Général Adjoint 1(SGA1)'), ('Sécrétaire Général Adjoint 2(SGA2)', 'Sécrétaire Général Adjoint 2(SGA2)'), ('Conseillé technique(CT)', 'Conseillé technique(CT)'), ('Chargé de mission(CM)', 'Chargé de mission(CM)'), ('Direction des missions internationales(DMI)', 'Direction des missions internationales(DMI)'), ('Direction des servides techniques commun(DSTC)', 'Direction des servides techniques commun(DSTC)'), ('Direction du budget de la solde(DBS)', 'Direction du budget de la solde(DBS)'), ('Direction agence comptable(AC)', 'Direction agence comptable(AC)'), ('Direction des actions sociales et médicales(DASM)', 'Direction des actions sociales et médicales(DASM)'), ("Direction de la traduction de l'interpretation(DTI)", "Direction de la traduction de l'interpretation(DTI)"), ('Direction de la coordination des services ratachés et des relations internationales', 'Direction de la coordination des services ratachés et des relations internationales'), ('Direction de la collectivité territorial décentralisées(DCTD)', 'Direction de la collectivité territorial décentralisées(DCTD)'), ('Direction des ressources humaines(DRH)', 'Direction des ressources humaines(DRH)'), ('Sercice du doyen', 'Sercice du doyen'), ('Sercice de la scolarité', 'Sercice de la scolarité'), ('Chef de département', 'Chef de département'), ('Sercice des questeurs', 'Sercice des questeurs')], max_length=150)),
                ('mention', models.CharField(blank=True, choices=[('ACCORD', 'ACCORD'), ('ETUDE ET COMPTE RENDU', 'ETUDE ET COMPTE RENDU'), ('ME VOIR', 'ME VOIR'), ('M EN PARLER', 'M EN PARLER'), ('REJET', 'REJET'), ('AUTRES', 'AUTRES')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courrier',
            },
        ),
    ]
