# Generated by Django 4.1.3 on 2022-11-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courrier',
            old_name='reciever',
            new_name='recepteur',
        ),
        migrations.RenameField(
            model_name='courrier',
            old_name='transmitter',
            new_name='transmetteur',
        ),
    ]
