# Generated by Django 4.1.4 on 2023-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
