# Generated by Django 4.1.4 on 2023-03-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0002_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebcamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webcam/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
