# Generated by Django 4.1.3 on 2022-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0003_courrier_annee_courrier_mention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='structure',
            field=models.CharField(blank=True, choices=[('SENAT', 'SENAT'), ('UNIVERSITE DE YAOUNDE 1', 'UNIVERSITE DE YAOUNDE 1')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='courrier',
            table='courrier',
        ),
    ]
