# Generated by Django 4.1.3 on 2022-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0004_alter_courrier_structure_alter_courrier_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='mention',
            field=models.CharField(blank=True, choices=[('ACCORD', 'ACCORD'), ('ETUDE ET COMPTE RENDU', 'ETUDE ET COMPTE RENDU'), ('ME VOIR', 'ME VOIR'), ('M EN PARLER', 'M EN PARLER'), ('REJET', 'REJET'), ('AUTRES', 'AUTRES')], max_length=100, null=True),
        ),
    ]
