
# Generated by Django 4.1.4 on 2023-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0005_alter_courrier_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]